version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER:-user}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-password}"
      POSTGRES_DB: "${DB_NAME:-raizes_nordeste}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-raizes_nordeste}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - raizes-nordeste
  app:
   build: .
   container_name: raizes_app
   ports:
     - "8080:8080"
   environment:
      DB_HOST: postgres_db
      DB_USER: "${DB_USER:-user}"
      DB_PASSWORD: "${DB_PASSWORD:-password}"
      DB_NAME: "${DB_NAME:-raizes_nordeste}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD:-password}"
      SECRET: "${JWT_SECRET:-2bd3855646db537030105d119dbdf37d39b16fb174dafbaa1424d8441b1671a9}"
   depends_on:
      db:
        condition: service_healthy
   networks:
     - raizes-nordeste

volumes:
  postgres_data:

networks:
  raizes-nordeste:
    driver: bridge