spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres_db}:${DB_PORT:5432}/${DB_NAME:raizes_nordeste}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: src/main/resources/db/migration/V1_init.sql
    flyway:
      enabled: true
      locations: classpath:db/migrations
jwt:
  secret: ${SECRET:jwt_secret}